### PR TITLE
Update snake.d.ts

### LINKED ISSUE #101: Faulty CartGiftCardItemSnake Type
Here is some misstake:
https://github.com/swellstores/swell-js/blob/master/types/cart/snake.d.ts#L34

Why is such a version with such errors even published?

### PR DESCRIPTION
**Pull request by BelphegorPrime**
fixes #101

### CODE REVIEW

**Review by ericingram — APPROVED** [review]

**Comment by igor-augustynski-furba** [comment]
Has this been merged? Still no new packages available on npm.

**Comment by ericingram** [comment]
Looks like it was closed instead of merged. We'll be publishing a patch version later today in any case

**Comment by igor-augustynski-furba** [comment]
The version You guys published (3.22.1) still has this issue.

**Comment by igor-augustynski-furba** [comment]
@ericingram Can we expect 3.22.2 today?

**Comment by ericingram** [comment]
Not likely today but soon

**Pull request merged**
